# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a999b0bace487ba89974d795a3a920bac37dc111c12dd56261dd237cd7eb7fc83120a4e3efb68e5d96dd725d5e4fc1b691be6b7acdccad3a30aec1174287857

test:
  secret_key_base: a89e4cc7ce0f294408ae714fc9983e546ba343a5d28957693f4f9c35a906a266349eca1985896ca570f15b7576e95db741670d514dcea00a335e7b7af254024f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
